//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id { get; set; }
        public Nullable<decimal> limitecredito { get; set; }
        public Nullable<int> idPessoa { get; set; }
        public Nullable<decimal> totalComprado { get; set; }
        public Nullable<System.DateTime> DataUltimoPagamento { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
