//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContasAPagar
    {
        public int id { get; set; }
        public Nullable<decimal> SomaSalarios { get; set; }
        public Nullable<decimal> SomaDividas { get; set; }
        public Nullable<decimal> SomaPedidos { get; set; }
    }
}
