//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluxoCaixa
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public Nullable<System.DateTime> DataFechamento { get; set; }
        public Nullable<decimal> ValorAbertura { get; set; }
        public Nullable<decimal> ValorFechamento { get; set; }
        public Nullable<decimal> Fluxo { get; set; }
    }
}
