//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPermissoes
    {
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idPermissao { get; set; }
        public int id { get; set; }
    
        public virtual Permissoes Permissoes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
