//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venda()
        {
            this.ItensVenda = new HashSet<ItensVenda>();
        }
    
        public int id { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> valorrestante { get; set; }
        public Nullable<int> idCategoriaPagamento { get; set; }
        public Nullable<int> qtdParcelas { get; set; }
        public string status { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensVenda> ItensVenda { get; set; }
        public virtual CategoriaPagamento CategoriaPagamento { get; set; }
    }
}
